// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from common.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class ArmEffectInfo implements Externalizable, Message<ArmEffectInfo>, Schema<ArmEffectInfo>
{

    public static Schema<ArmEffectInfo> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static ArmEffectInfo getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ArmEffectInfo DEFAULT_INSTANCE = new ArmEffectInfo();

    
    private Integer id;
    private Integer level;
    private Integer exp;

    public ArmEffectInfo()
    {
        
    }

    // getters and setters

    // id

    public boolean hasId(){
        return id != null;
    }


    public Integer getId()
    {
        return id == null ? 0 : id;
    }

    public ArmEffectInfo setId(Integer id)
    {
        this.id = id;
        return this;
    }

    // level

    public boolean hasLevel(){
        return level != null;
    }


    public Integer getLevel()
    {
        return level == null ? 0 : level;
    }

    public ArmEffectInfo setLevel(Integer level)
    {
        this.level = level;
        return this;
    }

    // exp

    public boolean hasExp(){
        return exp != null;
    }


    public Integer getExp()
    {
        return exp == null ? 0 : exp;
    }

    public ArmEffectInfo setExp(Integer exp)
    {
        this.exp = exp;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<ArmEffectInfo> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public ArmEffectInfo newMessage()
    {
        return new ArmEffectInfo();
    }

    public Class<ArmEffectInfo> typeClass()
    {
        return ArmEffectInfo.class;
    }

    public String messageName()
    {
        return ArmEffectInfo.class.getSimpleName();
    }

    public String messageFullName()
    {
        return ArmEffectInfo.class.getName();
    }

    public boolean isInitialized(ArmEffectInfo message)
    {
        return true;
    }

    public void mergeFrom(Input input, ArmEffectInfo message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.id = input.readUInt32();
                    break;
                case 20:
                    message.level = input.readUInt32();
                    break;
                case 30:
                    message.exp = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, ArmEffectInfo message) throws IOException
    {
        if(message.id != null)
            output.writeUInt32(10, message.id, false);

        if(message.level != null)
            output.writeUInt32(20, message.level, false);

        if(message.exp != null)
            output.writeUInt32(30, message.exp, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
