// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from common.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class BattleIdInfo implements Externalizable, Message<BattleIdInfo>, Schema<BattleIdInfo>
{

    public static Schema<BattleIdInfo> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static BattleIdInfo getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final BattleIdInfo DEFAULT_INSTANCE = new BattleIdInfo();

    
    private BaseBattleIdInfo bi;

    public BattleIdInfo()
    {
        
    }

    // getters and setters

    // bi

    public boolean hasBi(){
        return bi != null;
    }


    public BaseBattleIdInfo getBi()
    {
        return bi == null ? new BaseBattleIdInfo() : bi;
    }

    public BattleIdInfo setBi(BaseBattleIdInfo bi)
    {
        this.bi = bi;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<BattleIdInfo> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public BattleIdInfo newMessage()
    {
        return new BattleIdInfo();
    }

    public Class<BattleIdInfo> typeClass()
    {
        return BattleIdInfo.class;
    }

    public String messageName()
    {
        return BattleIdInfo.class.getSimpleName();
    }

    public String messageFullName()
    {
        return BattleIdInfo.class.getName();
    }

    public boolean isInitialized(BattleIdInfo message)
    {
        return true;
    }

    public void mergeFrom(Input input, BattleIdInfo message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.bi = input.mergeObject(message.bi, BaseBattleIdInfo.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, BattleIdInfo message) throws IOException
    {
        if(message.bi != null)
             output.writeObject(10, message.bi, BaseBattleIdInfo.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
