// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from common.proto

package com.vikings.sanguo.protos;

public enum BattleLogReturnInfoType implements com.dyuproject.protostuff.EnumLite<BattleLogReturnInfoType>
{
    E_BATTLE_LOG_RETURN_DUNGEON_PASS(1),
    E_BATTLE_LOG_RETURN_DUNGEON_RECORD(2),
    E_BATTLE_LOG_RETURN_DUNGEON_ACCIDENT(3),
    E_BATTLE_LOG_RETURN_DROP(4),
    E_BATTLE_LOG_RETURN_PLUNDER(5);
    
    public final int number;
    
    private BattleLogReturnInfoType (int number)
    {
        this.number = number;
    }
    
    public int getNumber()
    {
        return number;
    }
    
    public static BattleLogReturnInfoType valueOf(int number)
    {
        switch(number) 
        {
            case 1: return E_BATTLE_LOG_RETURN_DUNGEON_PASS;
            case 2: return E_BATTLE_LOG_RETURN_DUNGEON_RECORD;
            case 3: return E_BATTLE_LOG_RETURN_DUNGEON_ACCIDENT;
            case 4: return E_BATTLE_LOG_RETURN_DROP;
            case 5: return E_BATTLE_LOG_RETURN_PLUNDER;
            default: return null;
        }
    }
}
