// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from common.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class BattleLogReturnInfo implements Externalizable, Message<BattleLogReturnInfo>, Schema<BattleLogReturnInfo>
{

    public static Schema<BattleLogReturnInfo> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static BattleLogReturnInfo getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final BattleLogReturnInfo DEFAULT_INSTANCE = new BattleLogReturnInfo();

    
    private Integer type;
    private ReturnInfo info;

    public BattleLogReturnInfo()
    {
        
    }

    // getters and setters

    // type

    public boolean hasType(){
        return type != null;
    }


    public Integer getType()
    {
        return type == null ? 0 : type;
    }

    public BattleLogReturnInfo setType(Integer type)
    {
        this.type = type;
        return this;
    }

    // info

    public boolean hasInfo(){
        return info != null;
    }


    public ReturnInfo getInfo()
    {
        return info == null ? new ReturnInfo() : info;
    }

    public BattleLogReturnInfo setInfo(ReturnInfo info)
    {
        this.info = info;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<BattleLogReturnInfo> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public BattleLogReturnInfo newMessage()
    {
        return new BattleLogReturnInfo();
    }

    public Class<BattleLogReturnInfo> typeClass()
    {
        return BattleLogReturnInfo.class;
    }

    public String messageName()
    {
        return BattleLogReturnInfo.class.getSimpleName();
    }

    public String messageFullName()
    {
        return BattleLogReturnInfo.class.getName();
    }

    public boolean isInitialized(BattleLogReturnInfo message)
    {
        return true;
    }

    public void mergeFrom(Input input, BattleLogReturnInfo message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.type = input.readUInt32();
                    break;
                case 20:
                    message.info = input.mergeObject(message.info, ReturnInfo.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, BattleLogReturnInfo message) throws IOException
    {
        if(message.type != null)
            output.writeUInt32(10, message.type, false);

        if(message.info != null)
             output.writeObject(20, message.info, ReturnInfo.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
