// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from common.proto

package com.vikings.sanguo.protos;

public enum BUILDING_EFFECT implements com.dyuproject.protostuff.EnumLite<BUILDING_EFFECT>
{
    BUILDING_EFFECT_POP_TOTAL(51),
    BUILDING_EFFECT_ARM_TOTAL(53),
    BUILDING_EFFECT_CELLAR_TOTAL(55),
    BUILDING_EFFECT_SCALE_VALUE(57),
    BUILDING_EFFECT_SITE_TOTAL(58),
    BUILDING_EFFECT_REVIVE_COUNT(59),
    BUILDING_EFFECT_ARM_HP_ADD(60),
    BUILDING_EFFECT_REVIVE_BOSS_COUNT(61),
    BUILDING_EFFECT_MONEY_SPEED(71),
    BUILDING_EFFECT_FOOD_SPEED(72),
    BUILDING_EFFECT_WOOD_SPEED(73),
    BUILDING_EFFECT_MATERIAL0_SPEED(74),
    BUILDING_EFFECT_MATERIAL1_SPEED(75),
    BUILDING_EFFECT_BATTLE_SKILLID(101),
    BUILDING_EFFECT_ARMID(102);
    
    public final int number;
    
    private BUILDING_EFFECT (int number)
    {
        this.number = number;
    }
    
    public int getNumber()
    {
        return number;
    }
    
    public static BUILDING_EFFECT valueOf(int number)
    {
        switch(number) 
        {
            case 51: return BUILDING_EFFECT_POP_TOTAL;
            case 53: return BUILDING_EFFECT_ARM_TOTAL;
            case 55: return BUILDING_EFFECT_CELLAR_TOTAL;
            case 57: return BUILDING_EFFECT_SCALE_VALUE;
            case 58: return BUILDING_EFFECT_SITE_TOTAL;
            case 59: return BUILDING_EFFECT_REVIVE_COUNT;
            case 60: return BUILDING_EFFECT_ARM_HP_ADD;
            case 61: return BUILDING_EFFECT_REVIVE_BOSS_COUNT;
            case 71: return BUILDING_EFFECT_MONEY_SPEED;
            case 72: return BUILDING_EFFECT_FOOD_SPEED;
            case 73: return BUILDING_EFFECT_WOOD_SPEED;
            case 74: return BUILDING_EFFECT_MATERIAL0_SPEED;
            case 75: return BUILDING_EFFECT_MATERIAL1_SPEED;
            case 101: return BUILDING_EFFECT_BATTLE_SKILLID;
            case 102: return BUILDING_EFFECT_ARMID;
            default: return null;
        }
    }
}
