// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from common.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class ExActInfo implements Externalizable, Message<ExActInfo>, Schema<ExActInfo>
{

    public static Schema<ExActInfo> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static ExActInfo getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ExActInfo DEFAULT_INSTANCE = new ExActInfo();

    
    private DataCtrl ctrl;
    private ActInfo info;

    public ExActInfo()
    {
        
    }

    // getters and setters

    // ctrl

    public boolean hasCtrl(){
        return ctrl != null;
    }


    public DataCtrl getCtrl()
    {
        return ctrl == null ? new DataCtrl() : ctrl;
    }

    public ExActInfo setCtrl(DataCtrl ctrl)
    {
        this.ctrl = ctrl;
        return this;
    }

    // info

    public boolean hasInfo(){
        return info != null;
    }


    public ActInfo getInfo()
    {
        return info == null ? new ActInfo() : info;
    }

    public ExActInfo setInfo(ActInfo info)
    {
        this.info = info;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<ExActInfo> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public ExActInfo newMessage()
    {
        return new ExActInfo();
    }

    public Class<ExActInfo> typeClass()
    {
        return ExActInfo.class;
    }

    public String messageName()
    {
        return ExActInfo.class.getSimpleName();
    }

    public String messageFullName()
    {
        return ExActInfo.class.getName();
    }

    public boolean isInitialized(ExActInfo message)
    {
        return true;
    }

    public void mergeFrom(Input input, ExActInfo message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.ctrl = input.mergeObject(message.ctrl, DataCtrl.getSchema());
                    break;

                case 20:
                    message.info = input.mergeObject(message.info, ActInfo.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, ExActInfo message) throws IOException
    {
        if(message.ctrl != null)
             output.writeObject(10, message.ctrl, DataCtrl.getSchema(), false);


        if(message.info != null)
             output.writeObject(20, message.info, ActInfo.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
