// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from common.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class ExArmPropInfo implements Externalizable, Message<ExArmPropInfo>, Schema<ExArmPropInfo>
{

    public static Schema<ExArmPropInfo> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static ExArmPropInfo getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ExArmPropInfo DEFAULT_INSTANCE = new ExArmPropInfo();

    
    private DataCtrl ctrl;
    private ArmPropInfo info;

    public ExArmPropInfo()
    {
        
    }

    // getters and setters

    // ctrl

    public boolean hasCtrl(){
        return ctrl != null;
    }


    public DataCtrl getCtrl()
    {
        return ctrl == null ? new DataCtrl() : ctrl;
    }

    public ExArmPropInfo setCtrl(DataCtrl ctrl)
    {
        this.ctrl = ctrl;
        return this;
    }

    // info

    public boolean hasInfo(){
        return info != null;
    }


    public ArmPropInfo getInfo()
    {
        return info == null ? new ArmPropInfo() : info;
    }

    public ExArmPropInfo setInfo(ArmPropInfo info)
    {
        this.info = info;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<ExArmPropInfo> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public ExArmPropInfo newMessage()
    {
        return new ExArmPropInfo();
    }

    public Class<ExArmPropInfo> typeClass()
    {
        return ExArmPropInfo.class;
    }

    public String messageName()
    {
        return ExArmPropInfo.class.getSimpleName();
    }

    public String messageFullName()
    {
        return ExArmPropInfo.class.getName();
    }

    public boolean isInitialized(ExArmPropInfo message)
    {
        return true;
    }

    public void mergeFrom(Input input, ExArmPropInfo message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.ctrl = input.mergeObject(message.ctrl, DataCtrl.getSchema());
                    break;

                case 20:
                    message.info = input.mergeObject(message.info, ArmPropInfo.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, ExArmPropInfo message) throws IOException
    {
        if(message.ctrl != null)
             output.writeObject(10, message.ctrl, DataCtrl.getSchema(), false);


        if(message.info != null)
             output.writeObject(20, message.info, ArmPropInfo.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
