// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from common.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class ExFriendInfo implements Externalizable, Message<ExFriendInfo>, Schema<ExFriendInfo>
{

    public static Schema<ExFriendInfo> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static ExFriendInfo getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ExFriendInfo DEFAULT_INSTANCE = new ExFriendInfo();

    
    private DataCtrl ctrl;
    private FriendInfo info;

    public ExFriendInfo()
    {
        
    }

    // getters and setters

    // ctrl

    public boolean hasCtrl(){
        return ctrl != null;
    }


    public DataCtrl getCtrl()
    {
        return ctrl == null ? new DataCtrl() : ctrl;
    }

    public ExFriendInfo setCtrl(DataCtrl ctrl)
    {
        this.ctrl = ctrl;
        return this;
    }

    // info

    public boolean hasInfo(){
        return info != null;
    }


    public FriendInfo getInfo()
    {
        return info == null ? new FriendInfo() : info;
    }

    public ExFriendInfo setInfo(FriendInfo info)
    {
        this.info = info;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<ExFriendInfo> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public ExFriendInfo newMessage()
    {
        return new ExFriendInfo();
    }

    public Class<ExFriendInfo> typeClass()
    {
        return ExFriendInfo.class;
    }

    public String messageName()
    {
        return ExFriendInfo.class.getSimpleName();
    }

    public String messageFullName()
    {
        return ExFriendInfo.class.getName();
    }

    public boolean isInitialized(ExFriendInfo message)
    {
        return true;
    }

    public void mergeFrom(Input input, ExFriendInfo message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.ctrl = input.mergeObject(message.ctrl, DataCtrl.getSchema());
                    break;

                case 20:
                    message.info = input.mergeObject(message.info, FriendInfo.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, ExFriendInfo message) throws IOException
    {
        if(message.ctrl != null)
             output.writeObject(10, message.ctrl, DataCtrl.getSchema(), false);


        if(message.info != null)
             output.writeObject(20, message.info, FriendInfo.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
