// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from common.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class ExGuildInviteInfo implements Externalizable, Message<ExGuildInviteInfo>, Schema<ExGuildInviteInfo>
{

    public static Schema<ExGuildInviteInfo> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static ExGuildInviteInfo getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ExGuildInviteInfo DEFAULT_INSTANCE = new ExGuildInviteInfo();

    
    private DataCtrl ctrl;
    private GuildInviteInfo info;

    public ExGuildInviteInfo()
    {
        
    }

    // getters and setters

    // ctrl

    public boolean hasCtrl(){
        return ctrl != null;
    }


    public DataCtrl getCtrl()
    {
        return ctrl == null ? new DataCtrl() : ctrl;
    }

    public ExGuildInviteInfo setCtrl(DataCtrl ctrl)
    {
        this.ctrl = ctrl;
        return this;
    }

    // info

    public boolean hasInfo(){
        return info != null;
    }


    public GuildInviteInfo getInfo()
    {
        return info == null ? new GuildInviteInfo() : info;
    }

    public ExGuildInviteInfo setInfo(GuildInviteInfo info)
    {
        this.info = info;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<ExGuildInviteInfo> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public ExGuildInviteInfo newMessage()
    {
        return new ExGuildInviteInfo();
    }

    public Class<ExGuildInviteInfo> typeClass()
    {
        return ExGuildInviteInfo.class;
    }

    public String messageName()
    {
        return ExGuildInviteInfo.class.getSimpleName();
    }

    public String messageFullName()
    {
        return ExGuildInviteInfo.class.getName();
    }

    public boolean isInitialized(ExGuildInviteInfo message)
    {
        return true;
    }

    public void mergeFrom(Input input, ExGuildInviteInfo message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.ctrl = input.mergeObject(message.ctrl, DataCtrl.getSchema());
                    break;

                case 20:
                    message.info = input.mergeObject(message.info, GuildInviteInfo.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, ExGuildInviteInfo message) throws IOException
    {
        if(message.ctrl != null)
             output.writeObject(10, message.ctrl, DataCtrl.getSchema(), false);


        if(message.info != null)
             output.writeObject(20, message.info, GuildInviteInfo.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
