// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from common.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class ExLordFiefInfo implements Externalizable, Message<ExLordFiefInfo>, Schema<ExLordFiefInfo>
{

    public static Schema<ExLordFiefInfo> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static ExLordFiefInfo getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ExLordFiefInfo DEFAULT_INSTANCE = new ExLordFiefInfo();

    
    private DataCtrl ctrl;
    private LordFiefInfo info;

    public ExLordFiefInfo()
    {
        
    }

    // getters and setters

    // ctrl

    public boolean hasCtrl(){
        return ctrl != null;
    }


    public DataCtrl getCtrl()
    {
        return ctrl == null ? new DataCtrl() : ctrl;
    }

    public ExLordFiefInfo setCtrl(DataCtrl ctrl)
    {
        this.ctrl = ctrl;
        return this;
    }

    // info

    public boolean hasInfo(){
        return info != null;
    }


    public LordFiefInfo getInfo()
    {
        return info == null ? new LordFiefInfo() : info;
    }

    public ExLordFiefInfo setInfo(LordFiefInfo info)
    {
        this.info = info;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<ExLordFiefInfo> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public ExLordFiefInfo newMessage()
    {
        return new ExLordFiefInfo();
    }

    public Class<ExLordFiefInfo> typeClass()
    {
        return ExLordFiefInfo.class;
    }

    public String messageName()
    {
        return ExLordFiefInfo.class.getSimpleName();
    }

    public String messageFullName()
    {
        return ExLordFiefInfo.class.getName();
    }

    public boolean isInitialized(ExLordFiefInfo message)
    {
        return true;
    }

    public void mergeFrom(Input input, ExLordFiefInfo message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.ctrl = input.mergeObject(message.ctrl, DataCtrl.getSchema());
                    break;

                case 20:
                    message.info = input.mergeObject(message.info, LordFiefInfo.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, ExLordFiefInfo message) throws IOException
    {
        if(message.ctrl != null)
             output.writeObject(10, message.ctrl, DataCtrl.getSchema(), false);


        if(message.info != null)
             output.writeObject(20, message.info, LordFiefInfo.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
