// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from common.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class ExUserTroopInfo implements Externalizable, Message<ExUserTroopInfo>, Schema<ExUserTroopInfo>
{

    public static Schema<ExUserTroopInfo> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static ExUserTroopInfo getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ExUserTroopInfo DEFAULT_INSTANCE = new ExUserTroopInfo();

    
    private DataCtrl ctrl;
    private UserTroopInfo info;

    public ExUserTroopInfo()
    {
        
    }

    // getters and setters

    // ctrl

    public boolean hasCtrl(){
        return ctrl != null;
    }


    public DataCtrl getCtrl()
    {
        return ctrl == null ? new DataCtrl() : ctrl;
    }

    public ExUserTroopInfo setCtrl(DataCtrl ctrl)
    {
        this.ctrl = ctrl;
        return this;
    }

    // info

    public boolean hasInfo(){
        return info != null;
    }


    public UserTroopInfo getInfo()
    {
        return info == null ? new UserTroopInfo() : info;
    }

    public ExUserTroopInfo setInfo(UserTroopInfo info)
    {
        this.info = info;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<ExUserTroopInfo> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public ExUserTroopInfo newMessage()
    {
        return new ExUserTroopInfo();
    }

    public Class<ExUserTroopInfo> typeClass()
    {
        return ExUserTroopInfo.class;
    }

    public String messageName()
    {
        return ExUserTroopInfo.class.getSimpleName();
    }

    public String messageFullName()
    {
        return ExUserTroopInfo.class.getName();
    }

    public boolean isInitialized(ExUserTroopInfo message)
    {
        return true;
    }

    public void mergeFrom(Input input, ExUserTroopInfo message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.ctrl = input.mergeObject(message.ctrl, DataCtrl.getSchema());
                    break;

                case 20:
                    message.info = input.mergeObject(message.info, UserTroopInfo.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, ExUserTroopInfo message) throws IOException
    {
        if(message.ctrl != null)
             output.writeObject(10, message.ctrl, DataCtrl.getSchema(), false);


        if(message.info != null)
             output.writeObject(20, message.info, UserTroopInfo.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
