// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from common.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class GuildSearchInfo implements Externalizable, Message<GuildSearchInfo>, Schema<GuildSearchInfo>
{

    public static Schema<GuildSearchInfo> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static GuildSearchInfo getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final GuildSearchInfo DEFAULT_INSTANCE = new GuildSearchInfo();

    
    private Integer id;
    private String name;
    private Integer image;
    private Integer members;
    private Integer level;
    private Integer leader;

    public GuildSearchInfo()
    {
        
    }

    // getters and setters

    // id

    public boolean hasId(){
        return id != null;
    }


    public Integer getId()
    {
        return id == null ? 0 : id;
    }

    public GuildSearchInfo setId(Integer id)
    {
        this.id = id;
        return this;
    }

    // name

    public boolean hasName(){
        return name != null;
    }


    public String getName()
    {
        return name == null ? "" : name;
    }

    public GuildSearchInfo setName(String name)
    {
        this.name = name;
        return this;
    }

    // image

    public boolean hasImage(){
        return image != null;
    }


    public Integer getImage()
    {
        return image == null ? 0 : image;
    }

    public GuildSearchInfo setImage(Integer image)
    {
        this.image = image;
        return this;
    }

    // members

    public boolean hasMembers(){
        return members != null;
    }


    public Integer getMembers()
    {
        return members == null ? 0 : members;
    }

    public GuildSearchInfo setMembers(Integer members)
    {
        this.members = members;
        return this;
    }

    // level

    public boolean hasLevel(){
        return level != null;
    }


    public Integer getLevel()
    {
        return level == null ? 0 : level;
    }

    public GuildSearchInfo setLevel(Integer level)
    {
        this.level = level;
        return this;
    }

    // leader

    public boolean hasLeader(){
        return leader != null;
    }


    public Integer getLeader()
    {
        return leader == null ? 0 : leader;
    }

    public GuildSearchInfo setLeader(Integer leader)
    {
        this.leader = leader;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<GuildSearchInfo> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public GuildSearchInfo newMessage()
    {
        return new GuildSearchInfo();
    }

    public Class<GuildSearchInfo> typeClass()
    {
        return GuildSearchInfo.class;
    }

    public String messageName()
    {
        return GuildSearchInfo.class.getSimpleName();
    }

    public String messageFullName()
    {
        return GuildSearchInfo.class.getName();
    }

    public boolean isInitialized(GuildSearchInfo message)
    {
        return true;
    }

    public void mergeFrom(Input input, GuildSearchInfo message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.id = input.readUInt32();
                    break;
                case 20:
                    message.name = input.readString();
                    break;
                case 30:
                    message.image = input.readUInt32();
                    break;
                case 40:
                    message.members = input.readUInt32();
                    break;
                case 50:
                    message.level = input.readUInt32();
                    break;
                case 60:
                    message.leader = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, GuildSearchInfo message) throws IOException
    {
        if(message.id != null)
            output.writeUInt32(10, message.id, false);

        if(message.name != null)
            output.writeString(20, message.name, false);

        if(message.image != null)
            output.writeUInt32(30, message.image, false);

        if(message.members != null)
            output.writeUInt32(40, message.members, false);

        if(message.level != null)
            output.writeUInt32(50, message.level, false);

        if(message.leader != null)
            output.writeUInt32(60, message.leader, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
