// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from common.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class GuildJoinInfos implements Externalizable, Message<GuildJoinInfos>, Schema<GuildJoinInfos>
{

    public static Schema<GuildJoinInfos> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static GuildJoinInfos getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final GuildJoinInfos DEFAULT_INSTANCE = new GuildJoinInfos();

    
    private DataCtrl ctrl;
    private List<ExGuildJoinInfo> infos;
    private Integer totalCount;

    public GuildJoinInfos()
    {
        
    }

    // getters and setters

    // ctrl

    public boolean hasCtrl(){
        return ctrl != null;
    }


    public DataCtrl getCtrl()
    {
        return ctrl == null ? new DataCtrl() : ctrl;
    }

    public GuildJoinInfos setCtrl(DataCtrl ctrl)
    {
        this.ctrl = ctrl;
        return this;
    }

    // infos

    public boolean hasInfos(){
        return infos != null;
    }


    public List<ExGuildJoinInfo> getInfosList()
    {
        return infos == null?  new ArrayList<ExGuildJoinInfo>():infos;
    }

    public int getInfosCount()
    {
        return infos == null?0:infos.size();
    }

    public ExGuildJoinInfo getInfos(int i)
    {
        return infos == null?null:infos.get(i);
    }


    public GuildJoinInfos setInfosList(List<ExGuildJoinInfo> infos)
    {
        this.infos = infos;
        return this;    
    }

    // totalCount

    public boolean hasTotalCount(){
        return totalCount != null;
    }


    public Integer getTotalCount()
    {
        return totalCount == null ? 0 : totalCount;
    }

    public GuildJoinInfos setTotalCount(Integer totalCount)
    {
        this.totalCount = totalCount;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<GuildJoinInfos> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public GuildJoinInfos newMessage()
    {
        return new GuildJoinInfos();
    }

    public Class<GuildJoinInfos> typeClass()
    {
        return GuildJoinInfos.class;
    }

    public String messageName()
    {
        return GuildJoinInfos.class.getSimpleName();
    }

    public String messageFullName()
    {
        return GuildJoinInfos.class.getName();
    }

    public boolean isInitialized(GuildJoinInfos message)
    {
        return true;
    }

    public void mergeFrom(Input input, GuildJoinInfos message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.ctrl = input.mergeObject(message.ctrl, DataCtrl.getSchema());
                    break;

                case 20:
                    if(message.infos == null)
                        message.infos = new ArrayList<ExGuildJoinInfo>();
                    message.infos.add(input.mergeObject(null, ExGuildJoinInfo.getSchema()));
                    break;

                case 30:
                    message.totalCount = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, GuildJoinInfos message) throws IOException
    {
        if(message.ctrl != null)
             output.writeObject(10, message.ctrl, DataCtrl.getSchema(), false);


        if(message.infos != null)
        {
            for(ExGuildJoinInfo infos : message.infos)
            {
                if(infos != null)
                    output.writeObject(20, infos, ExGuildJoinInfo.getSchema(), true);
            }
        }


        if(message.totalCount != null)
            output.writeUInt32(30, message.totalCount, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
