// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgPlayerManorUpdateReq implements Externalizable, Message<MsgPlayerManorUpdateReq>, Schema<MsgPlayerManorUpdateReq>
{

    public static Schema<MsgPlayerManorUpdateReq> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgPlayerManorUpdateReq getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgPlayerManorUpdateReq DEFAULT_INSTANCE = new MsgPlayerManorUpdateReq();

    
    private String name;

    public MsgPlayerManorUpdateReq()
    {
        
    }

    // getters and setters

    // name

    public boolean hasName(){
        return name != null;
    }


    public String getName()
    {
        return name == null ? "" : name;
    }

    public MsgPlayerManorUpdateReq setName(String name)
    {
        this.name = name;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgPlayerManorUpdateReq> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgPlayerManorUpdateReq newMessage()
    {
        return new MsgPlayerManorUpdateReq();
    }

    public Class<MsgPlayerManorUpdateReq> typeClass()
    {
        return MsgPlayerManorUpdateReq.class;
    }

    public String messageName()
    {
        return MsgPlayerManorUpdateReq.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgPlayerManorUpdateReq.class.getName();
    }

    public boolean isInitialized(MsgPlayerManorUpdateReq message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgPlayerManorUpdateReq message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.name = input.readString();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgPlayerManorUpdateReq message) throws IOException
    {
        if(message.name != null)
            output.writeString(10, message.name, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
