// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgRspBuildingReset implements Externalizable, Message<MsgRspBuildingReset>, Schema<MsgRspBuildingReset>
{

    public static Schema<MsgRspBuildingReset> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgRspBuildingReset getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgRspBuildingReset DEFAULT_INSTANCE = new MsgRspBuildingReset();

    
    private ReturnInfo ri;
    private BuildingInfo bi;

    public MsgRspBuildingReset()
    {
        
    }

    // getters and setters

    // ri

    public boolean hasRi(){
        return ri != null;
    }


    public ReturnInfo getRi()
    {
        return ri == null ? new ReturnInfo() : ri;
    }

    public MsgRspBuildingReset setRi(ReturnInfo ri)
    {
        this.ri = ri;
        return this;
    }

    // bi

    public boolean hasBi(){
        return bi != null;
    }


    public BuildingInfo getBi()
    {
        return bi == null ? new BuildingInfo() : bi;
    }

    public MsgRspBuildingReset setBi(BuildingInfo bi)
    {
        this.bi = bi;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgRspBuildingReset> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgRspBuildingReset newMessage()
    {
        return new MsgRspBuildingReset();
    }

    public Class<MsgRspBuildingReset> typeClass()
    {
        return MsgRspBuildingReset.class;
    }

    public String messageName()
    {
        return MsgRspBuildingReset.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgRspBuildingReset.class.getName();
    }

    public boolean isInitialized(MsgRspBuildingReset message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgRspBuildingReset message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.ri = input.mergeObject(message.ri, ReturnInfo.getSchema());
                    break;

                case 20:
                    message.bi = input.mergeObject(message.bi, BuildingInfo.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgRspBuildingReset message) throws IOException
    {
        if(message.ri != null)
             output.writeObject(10, message.ri, ReturnInfo.getSchema(), false);


        if(message.bi != null)
             output.writeObject(20, message.bi, BuildingInfo.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
