// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgRspManorRevive implements Externalizable, Message<MsgRspManorRevive>, Schema<MsgRspManorRevive>
{

    public static Schema<MsgRspManorRevive> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgRspManorRevive getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgRspManorRevive DEFAULT_INSTANCE = new MsgRspManorRevive();

    
    private ReturnInfo ri;
    private ManorInfo mi;
    private LordInfo li;

    public MsgRspManorRevive()
    {
        
    }

    // getters and setters

    // ri

    public boolean hasRi(){
        return ri != null;
    }


    public ReturnInfo getRi()
    {
        return ri == null ? new ReturnInfo() : ri;
    }

    public MsgRspManorRevive setRi(ReturnInfo ri)
    {
        this.ri = ri;
        return this;
    }

    // mi

    public boolean hasMi(){
        return mi != null;
    }


    public ManorInfo getMi()
    {
        return mi == null ? new ManorInfo() : mi;
    }

    public MsgRspManorRevive setMi(ManorInfo mi)
    {
        this.mi = mi;
        return this;
    }

    // li

    public boolean hasLi(){
        return li != null;
    }


    public LordInfo getLi()
    {
        return li == null ? new LordInfo() : li;
    }

    public MsgRspManorRevive setLi(LordInfo li)
    {
        this.li = li;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgRspManorRevive> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgRspManorRevive newMessage()
    {
        return new MsgRspManorRevive();
    }

    public Class<MsgRspManorRevive> typeClass()
    {
        return MsgRspManorRevive.class;
    }

    public String messageName()
    {
        return MsgRspManorRevive.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgRspManorRevive.class.getName();
    }

    public boolean isInitialized(MsgRspManorRevive message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgRspManorRevive message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.ri = input.mergeObject(message.ri, ReturnInfo.getSchema());
                    break;

                case 20:
                    message.mi = input.mergeObject(message.mi, ManorInfo.getSchema());
                    break;

                case 30:
                    message.li = input.mergeObject(message.li, LordInfo.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgRspManorRevive message) throws IOException
    {
        if(message.ri != null)
             output.writeObject(10, message.ri, ReturnInfo.getSchema(), false);


        if(message.mi != null)
             output.writeObject(20, message.mi, ManorInfo.getSchema(), false);


        if(message.li != null)
             output.writeObject(30, message.li, LordInfo.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
