// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgReqManorReceiveAll implements Externalizable, Message<MsgReqManorReceiveAll>, Schema<MsgReqManorReceiveAll>
{

    public static Schema<MsgReqManorReceiveAll> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgReqManorReceiveAll getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgReqManorReceiveAll DEFAULT_INSTANCE = new MsgReqManorReceiveAll();

    
    private Boolean receiveFief;

    public MsgReqManorReceiveAll()
    {
        
    }

    // getters and setters

    // receiveFief

    public boolean hasReceiveFief(){
        return receiveFief != null;
    }


    public Boolean getReceiveFief()
    {
        return receiveFief == null ? false : receiveFief;
    }

    public MsgReqManorReceiveAll setReceiveFief(Boolean receiveFief)
    {
        this.receiveFief = receiveFief;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgReqManorReceiveAll> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgReqManorReceiveAll newMessage()
    {
        return new MsgReqManorReceiveAll();
    }

    public Class<MsgReqManorReceiveAll> typeClass()
    {
        return MsgReqManorReceiveAll.class;
    }

    public String messageName()
    {
        return MsgReqManorReceiveAll.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgReqManorReceiveAll.class.getName();
    }

    public boolean isInitialized(MsgReqManorReceiveAll message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgReqManorReceiveAll message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 20:
                    message.receiveFief = input.readBool();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgReqManorReceiveAll message) throws IOException
    {
        if(message.receiveFief != null)
            output.writeBool(20, message.receiveFief, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
