// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgReqHeroSkillStudy implements Externalizable, Message<MsgReqHeroSkillStudy>, Schema<MsgReqHeroSkillStudy>
{

    public static Schema<MsgReqHeroSkillStudy> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgReqHeroSkillStudy getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgReqHeroSkillStudy DEFAULT_INSTANCE = new MsgReqHeroSkillStudy();

    
    private Long hero;
    private Integer slotid;
    private Integer skillid;

    public MsgReqHeroSkillStudy()
    {
        
    }

    // getters and setters

    // hero

    public boolean hasHero(){
        return hero != null;
    }


    public Long getHero()
    {
        return hero == null ? 0L : hero;
    }

    public MsgReqHeroSkillStudy setHero(Long hero)
    {
        this.hero = hero;
        return this;
    }

    // slotid

    public boolean hasSlotid(){
        return slotid != null;
    }


    public Integer getSlotid()
    {
        return slotid == null ? 0 : slotid;
    }

    public MsgReqHeroSkillStudy setSlotid(Integer slotid)
    {
        this.slotid = slotid;
        return this;
    }

    // skillid

    public boolean hasSkillid(){
        return skillid != null;
    }


    public Integer getSkillid()
    {
        return skillid == null ? 0 : skillid;
    }

    public MsgReqHeroSkillStudy setSkillid(Integer skillid)
    {
        this.skillid = skillid;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgReqHeroSkillStudy> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgReqHeroSkillStudy newMessage()
    {
        return new MsgReqHeroSkillStudy();
    }

    public Class<MsgReqHeroSkillStudy> typeClass()
    {
        return MsgReqHeroSkillStudy.class;
    }

    public String messageName()
    {
        return MsgReqHeroSkillStudy.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgReqHeroSkillStudy.class.getName();
    }

    public boolean isInitialized(MsgReqHeroSkillStudy message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgReqHeroSkillStudy message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.hero = input.readUInt64();
                    break;
                case 20:
                    message.slotid = input.readUInt32();
                    break;
                case 30:
                    message.skillid = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgReqHeroSkillStudy message) throws IOException
    {
        if(message.hero != null)
            output.writeUInt64(10, message.hero, false);

        if(message.slotid != null)
            output.writeUInt32(20, message.slotid, false);

        if(message.skillid != null)
            output.writeUInt32(30, message.skillid, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
