// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgReqMachinePlay implements Externalizable, Message<MsgReqMachinePlay>, Schema<MsgReqMachinePlay>
{

    public static Schema<MsgReqMachinePlay> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgReqMachinePlay getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgReqMachinePlay DEFAULT_INSTANCE = new MsgReqMachinePlay();

    
    private MachinePlayType type;

    public MsgReqMachinePlay()
    {
        
    }

    // getters and setters

    // type

    public boolean hasType(){
        return type != null;
    }


    public MachinePlayType getType()
    {
        return type == null ? MachinePlayType.MACHINE_PLAY_TYPE_JUNIOR : type;
    }

    public MsgReqMachinePlay setType(MachinePlayType type)
    {
        this.type = type;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgReqMachinePlay> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgReqMachinePlay newMessage()
    {
        return new MsgReqMachinePlay();
    }

    public Class<MsgReqMachinePlay> typeClass()
    {
        return MsgReqMachinePlay.class;
    }

    public String messageName()
    {
        return MsgReqMachinePlay.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgReqMachinePlay.class.getName();
    }

    public boolean isInitialized(MsgReqMachinePlay message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgReqMachinePlay message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.type = MachinePlayType.valueOf(input.readEnum());
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgReqMachinePlay message) throws IOException
    {
        if(message.type != null)
             output.writeEnum(10, message.type.number, false);}

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
