// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgRspAccountRestore2 implements Externalizable, Message<MsgRspAccountRestore2>, Schema<MsgRspAccountRestore2>
{

    public static Schema<MsgRspAccountRestore2> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgRspAccountRestore2 getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgRspAccountRestore2 DEFAULT_INSTANCE = new MsgRspAccountRestore2();

    
    private List<AccountPswInfo> infos;

    public MsgRspAccountRestore2()
    {
        
    }

    // getters and setters

    // infos

    public boolean hasInfos(){
        return infos != null;
    }


    public List<AccountPswInfo> getInfosList()
    {
        return infos == null?  new ArrayList<AccountPswInfo>():infos;
    }

    public int getInfosCount()
    {
        return infos == null?0:infos.size();
    }

    public AccountPswInfo getInfos(int i)
    {
        return infos == null?null:infos.get(i);
    }


    public MsgRspAccountRestore2 setInfosList(List<AccountPswInfo> infos)
    {
        this.infos = infos;
        return this;    
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgRspAccountRestore2> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgRspAccountRestore2 newMessage()
    {
        return new MsgRspAccountRestore2();
    }

    public Class<MsgRspAccountRestore2> typeClass()
    {
        return MsgRspAccountRestore2.class;
    }

    public String messageName()
    {
        return MsgRspAccountRestore2.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgRspAccountRestore2.class.getName();
    }

    public boolean isInitialized(MsgRspAccountRestore2 message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgRspAccountRestore2 message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 30:
                    if(message.infos == null)
                        message.infos = new ArrayList<AccountPswInfo>();
                    message.infos.add(input.mergeObject(null, AccountPswInfo.getSchema()));
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgRspAccountRestore2 message) throws IOException
    {
        if(message.infos != null)
        {
            for(AccountPswInfo infos : message.infos)
            {
                if(infos != null)
                    output.writeObject(30, infos, AccountPswInfo.getSchema(), true);
            }
        }

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
