// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgRspHotUserAttrScoreInfoQuery implements Externalizable, Message<MsgRspHotUserAttrScoreInfoQuery>, Schema<MsgRspHotUserAttrScoreInfoQuery>
{

    public static Schema<MsgRspHotUserAttrScoreInfoQuery> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgRspHotUserAttrScoreInfoQuery getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgRspHotUserAttrScoreInfoQuery DEFAULT_INSTANCE = new MsgRspHotUserAttrScoreInfoQuery();

    
    private List<BriefFiefInfo> infos;
    private List<HotUserScoreInfo> hotInfos;
    private Integer total;

    public MsgRspHotUserAttrScoreInfoQuery()
    {
        
    }

    // getters and setters

    // infos

    public boolean hasInfos(){
        return infos != null;
    }


    public List<BriefFiefInfo> getInfosList()
    {
        return infos == null?  new ArrayList<BriefFiefInfo>():infos;
    }

    public int getInfosCount()
    {
        return infos == null?0:infos.size();
    }

    public BriefFiefInfo getInfos(int i)
    {
        return infos == null?null:infos.get(i);
    }


    public MsgRspHotUserAttrScoreInfoQuery setInfosList(List<BriefFiefInfo> infos)
    {
        this.infos = infos;
        return this;    
    }

    // hotInfos

    public boolean hasHotInfos(){
        return hotInfos != null;
    }


    public List<HotUserScoreInfo> getHotInfosList()
    {
        return hotInfos == null?  new ArrayList<HotUserScoreInfo>():hotInfos;
    }

    public int getHotInfosCount()
    {
        return hotInfos == null?0:hotInfos.size();
    }

    public HotUserScoreInfo getHotInfos(int i)
    {
        return hotInfos == null?null:hotInfos.get(i);
    }


    public MsgRspHotUserAttrScoreInfoQuery setHotInfosList(List<HotUserScoreInfo> hotInfos)
    {
        this.hotInfos = hotInfos;
        return this;    
    }

    // total

    public boolean hasTotal(){
        return total != null;
    }


    public Integer getTotal()
    {
        return total == null ? 0 : total;
    }

    public MsgRspHotUserAttrScoreInfoQuery setTotal(Integer total)
    {
        this.total = total;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgRspHotUserAttrScoreInfoQuery> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgRspHotUserAttrScoreInfoQuery newMessage()
    {
        return new MsgRspHotUserAttrScoreInfoQuery();
    }

    public Class<MsgRspHotUserAttrScoreInfoQuery> typeClass()
    {
        return MsgRspHotUserAttrScoreInfoQuery.class;
    }

    public String messageName()
    {
        return MsgRspHotUserAttrScoreInfoQuery.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgRspHotUserAttrScoreInfoQuery.class.getName();
    }

    public boolean isInitialized(MsgRspHotUserAttrScoreInfoQuery message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgRspHotUserAttrScoreInfoQuery message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    if(message.infos == null)
                        message.infos = new ArrayList<BriefFiefInfo>();
                    message.infos.add(input.mergeObject(null, BriefFiefInfo.getSchema()));
                    break;

                case 20:
                    if(message.hotInfos == null)
                        message.hotInfos = new ArrayList<HotUserScoreInfo>();
                    message.hotInfos.add(input.mergeObject(null, HotUserScoreInfo.getSchema()));
                    break;

                case 30:
                    message.total = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgRspHotUserAttrScoreInfoQuery message) throws IOException
    {
        if(message.infos != null)
        {
            for(BriefFiefInfo infos : message.infos)
            {
                if(infos != null)
                    output.writeObject(10, infos, BriefFiefInfo.getSchema(), true);
            }
        }


        if(message.hotInfos != null)
        {
            for(HotUserScoreInfo hotInfos : message.hotInfos)
            {
                if(hotInfos != null)
                    output.writeObject(20, hotInfos, HotUserScoreInfo.getSchema(), true);
            }
        }


        if(message.total != null)
            output.writeUInt32(30, message.total, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
