// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgRspDungeonDivine implements Externalizable, Message<MsgRspDungeonDivine>, Schema<MsgRspDungeonDivine>
{

    public static Schema<MsgRspDungeonDivine> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgRspDungeonDivine getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgRspDungeonDivine DEFAULT_INSTANCE = new MsgRspDungeonDivine();

    
    private Integer divineResult;
    private ReturnInfo ri;

    public MsgRspDungeonDivine()
    {
        
    }

    // getters and setters

    // divineResult

    public boolean hasDivineResult(){
        return divineResult != null;
    }


    public Integer getDivineResult()
    {
        return divineResult == null ? 0 : divineResult;
    }

    public MsgRspDungeonDivine setDivineResult(Integer divineResult)
    {
        this.divineResult = divineResult;
        return this;
    }

    // ri

    public boolean hasRi(){
        return ri != null;
    }


    public ReturnInfo getRi()
    {
        return ri == null ? new ReturnInfo() : ri;
    }

    public MsgRspDungeonDivine setRi(ReturnInfo ri)
    {
        this.ri = ri;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgRspDungeonDivine> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgRspDungeonDivine newMessage()
    {
        return new MsgRspDungeonDivine();
    }

    public Class<MsgRspDungeonDivine> typeClass()
    {
        return MsgRspDungeonDivine.class;
    }

    public String messageName()
    {
        return MsgRspDungeonDivine.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgRspDungeonDivine.class.getName();
    }

    public boolean isInitialized(MsgRspDungeonDivine message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgRspDungeonDivine message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.divineResult = input.readUInt32();
                    break;
                case 20:
                    message.ri = input.mergeObject(message.ri, ReturnInfo.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgRspDungeonDivine message) throws IOException
    {
        if(message.divineResult != null)
            output.writeUInt32(10, message.divineResult, false);

        if(message.ri != null)
             output.writeObject(20, message.ri, ReturnInfo.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
