// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgRspLordFiefIdQuery implements Externalizable, Message<MsgRspLordFiefIdQuery>, Schema<MsgRspLordFiefIdQuery>
{

    public static Schema<MsgRspLordFiefIdQuery> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgRspLordFiefIdQuery getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgRspLordFiefIdQuery DEFAULT_INSTANCE = new MsgRspLordFiefIdQuery();

    
    private List<Long> fiefids;

    public MsgRspLordFiefIdQuery()
    {
        
    }

    // getters and setters

    // fiefids

    public boolean hasFiefids(){
        return fiefids != null;
    }


    public List<Long> getFiefidsList()
    {
        return fiefids == null?  new ArrayList<Long>():fiefids;
    }

    public int getFiefidsCount()
    {
        return fiefids == null?0:fiefids.size();
    }

    public Long getFiefids(int i)
    {
        return fiefids == null?null:fiefids.get(i);
    }


    public MsgRspLordFiefIdQuery setFiefidsList(List<Long> fiefids)
    {
        this.fiefids = fiefids;
        return this;    
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgRspLordFiefIdQuery> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgRspLordFiefIdQuery newMessage()
    {
        return new MsgRspLordFiefIdQuery();
    }

    public Class<MsgRspLordFiefIdQuery> typeClass()
    {
        return MsgRspLordFiefIdQuery.class;
    }

    public String messageName()
    {
        return MsgRspLordFiefIdQuery.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgRspLordFiefIdQuery.class.getName();
    }

    public boolean isInitialized(MsgRspLordFiefIdQuery message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgRspLordFiefIdQuery message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    if(message.fiefids == null)
                        message.fiefids = new ArrayList<Long>();
                    int count = input.readInt32();
                    int cur = ((com.dyuproject.protostuff.ByteArrayInput)input).currentOffset();
                    while(((com.dyuproject.protostuff.ByteArrayInput)input).currentOffset() - cur < count)
                    {
                        message.fiefids.add(input.readUInt64());
                    }
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgRspLordFiefIdQuery message) throws IOException
    {
        if(message.fiefids != null)
        {
            for(Long fiefids : message.fiefids)
            {
                if(fiefids != null)
                    output.writeUInt64(10, fiefids, true);
            }
        }
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
