// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgRspRoulette implements Externalizable, Message<MsgRspRoulette>, Schema<MsgRspRoulette>
{

    public static Schema<MsgRspRoulette> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgRspRoulette getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgRspRoulette DEFAULT_INSTANCE = new MsgRspRoulette();

    
    private ReturnInfo ri;
    private List<KeyValue> infos;

    public MsgRspRoulette()
    {
        
    }

    // getters and setters

    // ri

    public boolean hasRi(){
        return ri != null;
    }


    public ReturnInfo getRi()
    {
        return ri == null ? new ReturnInfo() : ri;
    }

    public MsgRspRoulette setRi(ReturnInfo ri)
    {
        this.ri = ri;
        return this;
    }

    // infos

    public boolean hasInfos(){
        return infos != null;
    }


    public List<KeyValue> getInfosList()
    {
        return infos == null?  new ArrayList<KeyValue>():infos;
    }

    public int getInfosCount()
    {
        return infos == null?0:infos.size();
    }

    public KeyValue getInfos(int i)
    {
        return infos == null?null:infos.get(i);
    }


    public MsgRspRoulette setInfosList(List<KeyValue> infos)
    {
        this.infos = infos;
        return this;    
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgRspRoulette> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgRspRoulette newMessage()
    {
        return new MsgRspRoulette();
    }

    public Class<MsgRspRoulette> typeClass()
    {
        return MsgRspRoulette.class;
    }

    public String messageName()
    {
        return MsgRspRoulette.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgRspRoulette.class.getName();
    }

    public boolean isInitialized(MsgRspRoulette message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgRspRoulette message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.ri = input.mergeObject(message.ri, ReturnInfo.getSchema());
                    break;

                case 20:
                    if(message.infos == null)
                        message.infos = new ArrayList<KeyValue>();
                    message.infos.add(input.mergeObject(null, KeyValue.getSchema()));
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgRspRoulette message) throws IOException
    {
        if(message.ri != null)
             output.writeObject(10, message.ri, ReturnInfo.getSchema(), false);


        if(message.infos != null)
        {
            for(KeyValue infos : message.infos)
            {
                if(infos != null)
                    output.writeObject(20, infos, KeyValue.getSchema(), true);
            }
        }

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
