// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgReqAccountBinding implements Externalizable, Message<MsgReqAccountBinding>, Schema<MsgReqAccountBinding>
{

    public static Schema<MsgReqAccountBinding> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgReqAccountBinding getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgReqAccountBinding DEFAULT_INSTANCE = new MsgReqAccountBinding();

    
    private BindingType bindingType;
    private String value;

    public MsgReqAccountBinding()
    {
        
    }

    // getters and setters

    // bindingType

    public boolean hasBindingType(){
        return bindingType != null;
    }


    public BindingType getBindingType()
    {
        return bindingType == null ? BindingType.BINDING_MOBILE : bindingType;
    }

    public MsgReqAccountBinding setBindingType(BindingType bindingType)
    {
        this.bindingType = bindingType;
        return this;
    }

    // value

    public boolean hasValue(){
        return value != null;
    }


    public String getValue()
    {
        return value == null ? "" : value;
    }

    public MsgReqAccountBinding setValue(String value)
    {
        this.value = value;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgReqAccountBinding> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgReqAccountBinding newMessage()
    {
        return new MsgReqAccountBinding();
    }

    public Class<MsgReqAccountBinding> typeClass()
    {
        return MsgReqAccountBinding.class;
    }

    public String messageName()
    {
        return MsgReqAccountBinding.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgReqAccountBinding.class.getName();
    }

    public boolean isInitialized(MsgReqAccountBinding message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgReqAccountBinding message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.bindingType = BindingType.valueOf(input.readEnum());
                    break;
                case 20:
                    message.value = input.readString();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgReqAccountBinding message) throws IOException
    {
        if(message.bindingType != null)
             output.writeEnum(10, message.bindingType.number, false);

        if(message.value != null)
            output.writeString(20, message.value, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
