// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgRspOtherRichGuildInfoQuery implements Externalizable, Message<MsgRspOtherRichGuildInfoQuery>, Schema<MsgRspOtherRichGuildInfoQuery>
{

    public static Schema<MsgRspOtherRichGuildInfoQuery> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgRspOtherRichGuildInfoQuery getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgRspOtherRichGuildInfoQuery DEFAULT_INSTANCE = new MsgRspOtherRichGuildInfoQuery();

    
    private OtherRichGuildInfo info;

    public MsgRspOtherRichGuildInfoQuery()
    {
        
    }

    // getters and setters

    // info

    public boolean hasInfo(){
        return info != null;
    }


    public OtherRichGuildInfo getInfo()
    {
        return info == null ? new OtherRichGuildInfo() : info;
    }

    public MsgRspOtherRichGuildInfoQuery setInfo(OtherRichGuildInfo info)
    {
        this.info = info;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgRspOtherRichGuildInfoQuery> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgRspOtherRichGuildInfoQuery newMessage()
    {
        return new MsgRspOtherRichGuildInfoQuery();
    }

    public Class<MsgRspOtherRichGuildInfoQuery> typeClass()
    {
        return MsgRspOtherRichGuildInfoQuery.class;
    }

    public String messageName()
    {
        return MsgRspOtherRichGuildInfoQuery.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgRspOtherRichGuildInfoQuery.class.getName();
    }

    public boolean isInitialized(MsgRspOtherRichGuildInfoQuery message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgRspOtherRichGuildInfoQuery message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.info = input.mergeObject(message.info, OtherRichGuildInfo.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgRspOtherRichGuildInfoQuery message) throws IOException
    {
        if(message.info != null)
             output.writeObject(10, message.info, OtherRichGuildInfo.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
