// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgRspManorRecommendEmptySpace implements Externalizable, Message<MsgRspManorRecommendEmptySpace>, Schema<MsgRspManorRecommendEmptySpace>
{

    public static Schema<MsgRspManorRecommendEmptySpace> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgRspManorRecommendEmptySpace getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgRspManorRecommendEmptySpace DEFAULT_INSTANCE = new MsgRspManorRecommendEmptySpace();

    
    private Long pos;

    public MsgRspManorRecommendEmptySpace()
    {
        
    }

    // getters and setters

    // pos

    public boolean hasPos(){
        return pos != null;
    }


    public Long getPos()
    {
        return pos == null ? 0L : pos;
    }

    public MsgRspManorRecommendEmptySpace setPos(Long pos)
    {
        this.pos = pos;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgRspManorRecommendEmptySpace> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgRspManorRecommendEmptySpace newMessage()
    {
        return new MsgRspManorRecommendEmptySpace();
    }

    public Class<MsgRspManorRecommendEmptySpace> typeClass()
    {
        return MsgRspManorRecommendEmptySpace.class;
    }

    public String messageName()
    {
        return MsgRspManorRecommendEmptySpace.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgRspManorRecommendEmptySpace.class.getName();
    }

    public boolean isInitialized(MsgRspManorRecommendEmptySpace message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgRspManorRecommendEmptySpace message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.pos = input.readUInt64();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgRspManorRecommendEmptySpace message) throws IOException
    {
        if(message.pos != null)
            output.writeUInt64(10, message.pos, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
