// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgReqEquipmentBuy implements Externalizable, Message<MsgReqEquipmentBuy>, Schema<MsgReqEquipmentBuy>
{

    public static Schema<MsgReqEquipmentBuy> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgReqEquipmentBuy getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgReqEquipmentBuy DEFAULT_INSTANCE = new MsgReqEquipmentBuy();

    
    private Integer scheme;

    public MsgReqEquipmentBuy()
    {
        
    }

    // getters and setters

    // scheme

    public boolean hasScheme(){
        return scheme != null;
    }


    public Integer getScheme()
    {
        return scheme == null ? 0 : scheme;
    }

    public MsgReqEquipmentBuy setScheme(Integer scheme)
    {
        this.scheme = scheme;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgReqEquipmentBuy> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgReqEquipmentBuy newMessage()
    {
        return new MsgReqEquipmentBuy();
    }

    public Class<MsgReqEquipmentBuy> typeClass()
    {
        return MsgReqEquipmentBuy.class;
    }

    public String messageName()
    {
        return MsgReqEquipmentBuy.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgReqEquipmentBuy.class.getName();
    }

    public boolean isInitialized(MsgReqEquipmentBuy message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgReqEquipmentBuy message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.scheme = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgReqEquipmentBuy message) throws IOException
    {
        if(message.scheme != null)
            output.writeUInt32(10, message.scheme, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
