// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgRspUserStatusUpdate implements Externalizable, Message<MsgRspUserStatusUpdate>, Schema<MsgRspUserStatusUpdate>
{

    public static Schema<MsgRspUserStatusUpdate> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgRspUserStatusUpdate getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgRspUserStatusUpdate DEFAULT_INSTANCE = new MsgRspUserStatusUpdate();

    
    private RoleInfo roleInfo;
    private ReturnInfo ri;

    public MsgRspUserStatusUpdate()
    {
        
    }

    // getters and setters

    // roleInfo

    public boolean hasRoleInfo(){
        return roleInfo != null;
    }


    public RoleInfo getRoleInfo()
    {
        return roleInfo == null ? new RoleInfo() : roleInfo;
    }

    public MsgRspUserStatusUpdate setRoleInfo(RoleInfo roleInfo)
    {
        this.roleInfo = roleInfo;
        return this;
    }

    // ri

    public boolean hasRi(){
        return ri != null;
    }


    public ReturnInfo getRi()
    {
        return ri == null ? new ReturnInfo() : ri;
    }

    public MsgRspUserStatusUpdate setRi(ReturnInfo ri)
    {
        this.ri = ri;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgRspUserStatusUpdate> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgRspUserStatusUpdate newMessage()
    {
        return new MsgRspUserStatusUpdate();
    }

    public Class<MsgRspUserStatusUpdate> typeClass()
    {
        return MsgRspUserStatusUpdate.class;
    }

    public String messageName()
    {
        return MsgRspUserStatusUpdate.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgRspUserStatusUpdate.class.getName();
    }

    public boolean isInitialized(MsgRspUserStatusUpdate message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgRspUserStatusUpdate message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.roleInfo = input.mergeObject(message.roleInfo, RoleInfo.getSchema());
                    break;

                case 20:
                    message.ri = input.mergeObject(message.ri, ReturnInfo.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgRspUserStatusUpdate message) throws IOException
    {
        if(message.roleInfo != null)
             output.writeObject(10, message.roleInfo, RoleInfo.getSchema(), false);


        if(message.ri != null)
             output.writeObject(20, message.ri, ReturnInfo.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
