// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgReqArenaAttack implements Externalizable, Message<MsgReqArenaAttack>, Schema<MsgReqArenaAttack>
{

    public static Schema<MsgReqArenaAttack> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgReqArenaAttack getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgReqArenaAttack DEFAULT_INSTANCE = new MsgReqArenaAttack();

    
    private Integer target;
    private Integer targetPos;
    private Integer selfPos;

    public MsgReqArenaAttack()
    {
        
    }

    // getters and setters

    // target

    public boolean hasTarget(){
        return target != null;
    }


    public Integer getTarget()
    {
        return target == null ? 0 : target;
    }

    public MsgReqArenaAttack setTarget(Integer target)
    {
        this.target = target;
        return this;
    }

    // targetPos

    public boolean hasTargetPos(){
        return targetPos != null;
    }


    public Integer getTargetPos()
    {
        return targetPos == null ? 0 : targetPos;
    }

    public MsgReqArenaAttack setTargetPos(Integer targetPos)
    {
        this.targetPos = targetPos;
        return this;
    }

    // selfPos

    public boolean hasSelfPos(){
        return selfPos != null;
    }


    public Integer getSelfPos()
    {
        return selfPos == null ? 0 : selfPos;
    }

    public MsgReqArenaAttack setSelfPos(Integer selfPos)
    {
        this.selfPos = selfPos;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgReqArenaAttack> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgReqArenaAttack newMessage()
    {
        return new MsgReqArenaAttack();
    }

    public Class<MsgReqArenaAttack> typeClass()
    {
        return MsgReqArenaAttack.class;
    }

    public String messageName()
    {
        return MsgReqArenaAttack.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgReqArenaAttack.class.getName();
    }

    public boolean isInitialized(MsgReqArenaAttack message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgReqArenaAttack message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.target = input.readUInt32();
                    break;
                case 20:
                    message.targetPos = input.readUInt32();
                    break;
                case 30:
                    message.selfPos = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgReqArenaAttack message) throws IOException
    {
        if(message.target != null)
            output.writeUInt32(10, message.target, false);

        if(message.targetPos != null)
            output.writeUInt32(20, message.targetPos, false);

        if(message.selfPos != null)
            output.writeUInt32(30, message.selfPos, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
