// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.ByteString;
import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgReqAccountQuery implements Externalizable, Message<MsgReqAccountQuery>, Schema<MsgReqAccountQuery>
{

    public static Schema<MsgReqAccountQuery> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgReqAccountQuery getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgReqAccountQuery DEFAULT_INSTANCE = new MsgReqAccountQuery();

    
    private String sim;
    private ByteString key;

    public MsgReqAccountQuery()
    {
        
    }

    // getters and setters

    // sim

    public boolean hasSim(){
        return sim != null;
    }


    public String getSim()
    {
        return sim == null ? "" : sim;
    }

    public MsgReqAccountQuery setSim(String sim)
    {
        this.sim = sim;
        return this;
    }

    // key

    public boolean hasKey(){
        return key != null;
    }


    public ByteString getKey()
    {
        return key == null ? ByteString.bytesDefaultValue("") : key;
    }

    public MsgReqAccountQuery setKey(ByteString key)
    {
        this.key = key;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgReqAccountQuery> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgReqAccountQuery newMessage()
    {
        return new MsgReqAccountQuery();
    }

    public Class<MsgReqAccountQuery> typeClass()
    {
        return MsgReqAccountQuery.class;
    }

    public String messageName()
    {
        return MsgReqAccountQuery.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgReqAccountQuery.class.getName();
    }

    public boolean isInitialized(MsgReqAccountQuery message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgReqAccountQuery message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.sim = input.readString();
                    break;
                case 20:
                    message.key = input.readBytes();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgReqAccountQuery message) throws IOException
    {
        if(message.sim != null)
            output.writeString(10, message.sim, false);

        if(message.key != null)
            output.writeBytes(20, message.key, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
