// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgRspManorDraft implements Externalizable, Message<MsgRspManorDraft>, Schema<MsgRspManorDraft>
{

    public static Schema<MsgRspManorDraft> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgRspManorDraft getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgRspManorDraft DEFAULT_INSTANCE = new MsgRspManorDraft();

    
    private ReturnInfo ri;
    private ManorInfo mi;

    public MsgRspManorDraft()
    {
        
    }

    // getters and setters

    // ri

    public boolean hasRi(){
        return ri != null;
    }


    public ReturnInfo getRi()
    {
        return ri == null ? new ReturnInfo() : ri;
    }

    public MsgRspManorDraft setRi(ReturnInfo ri)
    {
        this.ri = ri;
        return this;
    }

    // mi

    public boolean hasMi(){
        return mi != null;
    }


    public ManorInfo getMi()
    {
        return mi == null ? new ManorInfo() : mi;
    }

    public MsgRspManorDraft setMi(ManorInfo mi)
    {
        this.mi = mi;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgRspManorDraft> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgRspManorDraft newMessage()
    {
        return new MsgRspManorDraft();
    }

    public Class<MsgRspManorDraft> typeClass()
    {
        return MsgRspManorDraft.class;
    }

    public String messageName()
    {
        return MsgRspManorDraft.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgRspManorDraft.class.getName();
    }

    public boolean isInitialized(MsgRspManorDraft message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgRspManorDraft message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.ri = input.mergeObject(message.ri, ReturnInfo.getSchema());
                    break;

                case 20:
                    message.mi = input.mergeObject(message.mi, ManorInfo.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgRspManorDraft message) throws IOException
    {
        if(message.ri != null)
             output.writeObject(10, message.ri, ReturnInfo.getSchema(), false);


        if(message.mi != null)
             output.writeObject(20, message.mi, ManorInfo.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
