// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgReqUserStaminaReset implements Externalizable, Message<MsgReqUserStaminaReset>, Schema<MsgReqUserStaminaReset>
{

    public static Schema<MsgReqUserStaminaReset> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgReqUserStaminaReset getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgReqUserStaminaReset DEFAULT_INSTANCE = new MsgReqUserStaminaReset();

    
    private Integer currency;

    public MsgReqUserStaminaReset()
    {
        
    }

    // getters and setters

    // currency

    public boolean hasCurrency(){
        return currency != null;
    }


    public Integer getCurrency()
    {
        return currency == null ? 0 : currency;
    }

    public MsgReqUserStaminaReset setCurrency(Integer currency)
    {
        this.currency = currency;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgReqUserStaminaReset> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgReqUserStaminaReset newMessage()
    {
        return new MsgReqUserStaminaReset();
    }

    public Class<MsgReqUserStaminaReset> typeClass()
    {
        return MsgReqUserStaminaReset.class;
    }

    public String messageName()
    {
        return MsgReqUserStaminaReset.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgReqUserStaminaReset.class.getName();
    }

    public boolean isInitialized(MsgReqUserStaminaReset message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgReqUserStaminaReset message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.currency = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgReqUserStaminaReset message) throws IOException
    {
        if(message.currency != null)
            output.writeUInt32(10, message.currency, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
