// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgReqHeroFavour implements Externalizable, Message<MsgReqHeroFavour>, Schema<MsgReqHeroFavour>
{

    public static Schema<MsgReqHeroFavour> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgReqHeroFavour getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgReqHeroFavour DEFAULT_INSTANCE = new MsgReqHeroFavour();

    
    private Long hero;
    private Integer slotid;

    public MsgReqHeroFavour()
    {
        
    }

    // getters and setters

    // hero

    public boolean hasHero(){
        return hero != null;
    }


    public Long getHero()
    {
        return hero == null ? 0L : hero;
    }

    public MsgReqHeroFavour setHero(Long hero)
    {
        this.hero = hero;
        return this;
    }

    // slotid

    public boolean hasSlotid(){
        return slotid != null;
    }


    public Integer getSlotid()
    {
        return slotid == null ? 0 : slotid;
    }

    public MsgReqHeroFavour setSlotid(Integer slotid)
    {
        this.slotid = slotid;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgReqHeroFavour> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgReqHeroFavour newMessage()
    {
        return new MsgReqHeroFavour();
    }

    public Class<MsgReqHeroFavour> typeClass()
    {
        return MsgReqHeroFavour.class;
    }

    public String messageName()
    {
        return MsgReqHeroFavour.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgReqHeroFavour.class.getName();
    }

    public boolean isInitialized(MsgReqHeroFavour message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgReqHeroFavour message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.hero = input.readUInt64();
                    break;
                case 20:
                    message.slotid = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgReqHeroFavour message) throws IOException
    {
        if(message.hero != null)
            output.writeUInt64(10, message.hero, false);

        if(message.slotid != null)
            output.writeUInt32(20, message.slotid, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
