// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgRspHeroAbandon implements Externalizable, Message<MsgRspHeroAbandon>, Schema<MsgRspHeroAbandon>
{

    public static Schema<MsgRspHeroAbandon> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgRspHeroAbandon getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgRspHeroAbandon DEFAULT_INSTANCE = new MsgRspHeroAbandon();

    
    private ReturnInfo info;

    public MsgRspHeroAbandon()
    {
        
    }

    // getters and setters

    // info

    public boolean hasInfo(){
        return info != null;
    }


    public ReturnInfo getInfo()
    {
        return info == null ? new ReturnInfo() : info;
    }

    public MsgRspHeroAbandon setInfo(ReturnInfo info)
    {
        this.info = info;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgRspHeroAbandon> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgRspHeroAbandon newMessage()
    {
        return new MsgRspHeroAbandon();
    }

    public Class<MsgRspHeroAbandon> typeClass()
    {
        return MsgRspHeroAbandon.class;
    }

    public String messageName()
    {
        return MsgRspHeroAbandon.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgRspHeroAbandon.class.getName();
    }

    public boolean isInitialized(MsgRspHeroAbandon message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgRspHeroAbandon message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.info = input.mergeObject(message.info, ReturnInfo.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgRspHeroAbandon message) throws IOException
    {
        if(message.info != null)
             output.writeObject(10, message.info, ReturnInfo.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
