// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgReqStaticUserDataQuery implements Externalizable, Message<MsgReqStaticUserDataQuery>, Schema<MsgReqStaticUserDataQuery>
{

    public static Schema<MsgReqStaticUserDataQuery> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgReqStaticUserDataQuery getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgReqStaticUserDataQuery DEFAULT_INSTANCE = new MsgReqStaticUserDataQuery();

    
    private StaticUserDataType dataType;
    private Long id;
    private Integer count;

    public MsgReqStaticUserDataQuery()
    {
        
    }

    // getters and setters

    // dataType

    public boolean hasDataType(){
        return dataType != null;
    }


    public StaticUserDataType getDataType()
    {
        return dataType == null ? StaticUserDataType.STATIC_USER_DATA_TYPE_LOG : dataType;
    }

    public MsgReqStaticUserDataQuery setDataType(StaticUserDataType dataType)
    {
        this.dataType = dataType;
        return this;
    }

    // id

    public boolean hasId(){
        return id != null;
    }


    public Long getId()
    {
        return id == null ? 0L : id;
    }

    public MsgReqStaticUserDataQuery setId(Long id)
    {
        this.id = id;
        return this;
    }

    // count

    public boolean hasCount(){
        return count != null;
    }


    public Integer getCount()
    {
        return count == null ? 0 : count;
    }

    public MsgReqStaticUserDataQuery setCount(Integer count)
    {
        this.count = count;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgReqStaticUserDataQuery> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgReqStaticUserDataQuery newMessage()
    {
        return new MsgReqStaticUserDataQuery();
    }

    public Class<MsgReqStaticUserDataQuery> typeClass()
    {
        return MsgReqStaticUserDataQuery.class;
    }

    public String messageName()
    {
        return MsgReqStaticUserDataQuery.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgReqStaticUserDataQuery.class.getName();
    }

    public boolean isInitialized(MsgReqStaticUserDataQuery message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgReqStaticUserDataQuery message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.dataType = StaticUserDataType.valueOf(input.readEnum());
                    break;
                case 20:
                    message.id = input.readUInt64();
                    break;
                case 30:
                    message.count = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgReqStaticUserDataQuery message) throws IOException
    {
        if(message.dataType != null)
             output.writeEnum(10, message.dataType.number, false);

        if(message.id != null)
            output.writeUInt64(20, message.id, false);

        if(message.count != null)
            output.writeUInt32(30, message.count, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
