// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgRspConfirmBuyBattleUnit implements Externalizable, Message<MsgRspConfirmBuyBattleUnit>, Schema<MsgRspConfirmBuyBattleUnit>
{

    public static Schema<MsgRspConfirmBuyBattleUnit> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgRspConfirmBuyBattleUnit getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgRspConfirmBuyBattleUnit DEFAULT_INSTANCE = new MsgRspConfirmBuyBattleUnit();

    
    private Integer pokerUnit;

    public MsgRspConfirmBuyBattleUnit()
    {
        
    }

    // getters and setters

    // pokerUnit

    public boolean hasPokerUnit(){
        return pokerUnit != null;
    }


    public Integer getPokerUnit()
    {
        return pokerUnit == null ? 0 : pokerUnit;
    }

    public MsgRspConfirmBuyBattleUnit setPokerUnit(Integer pokerUnit)
    {
        this.pokerUnit = pokerUnit;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgRspConfirmBuyBattleUnit> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgRspConfirmBuyBattleUnit newMessage()
    {
        return new MsgRspConfirmBuyBattleUnit();
    }

    public Class<MsgRspConfirmBuyBattleUnit> typeClass()
    {
        return MsgRspConfirmBuyBattleUnit.class;
    }

    public String messageName()
    {
        return MsgRspConfirmBuyBattleUnit.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgRspConfirmBuyBattleUnit.class.getName();
    }

    public boolean isInitialized(MsgRspConfirmBuyBattleUnit message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgRspConfirmBuyBattleUnit message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.pokerUnit = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgRspConfirmBuyBattleUnit message) throws IOException
    {
        if(message.pokerUnit != null)
            output.writeUInt32(10, message.pokerUnit, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
