// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgReqGuildInviteRemove implements Externalizable, Message<MsgReqGuildInviteRemove>, Schema<MsgReqGuildInviteRemove>
{

    public static Schema<MsgReqGuildInviteRemove> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgReqGuildInviteRemove getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgReqGuildInviteRemove DEFAULT_INSTANCE = new MsgReqGuildInviteRemove();

    
    private Integer guildid;
    private Integer target;

    public MsgReqGuildInviteRemove()
    {
        
    }

    // getters and setters

    // guildid

    public boolean hasGuildid(){
        return guildid != null;
    }


    public Integer getGuildid()
    {
        return guildid == null ? 0 : guildid;
    }

    public MsgReqGuildInviteRemove setGuildid(Integer guildid)
    {
        this.guildid = guildid;
        return this;
    }

    // target

    public boolean hasTarget(){
        return target != null;
    }


    public Integer getTarget()
    {
        return target == null ? 0 : target;
    }

    public MsgReqGuildInviteRemove setTarget(Integer target)
    {
        this.target = target;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgReqGuildInviteRemove> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgReqGuildInviteRemove newMessage()
    {
        return new MsgReqGuildInviteRemove();
    }

    public Class<MsgReqGuildInviteRemove> typeClass()
    {
        return MsgReqGuildInviteRemove.class;
    }

    public String messageName()
    {
        return MsgReqGuildInviteRemove.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgReqGuildInviteRemove.class.getName();
    }

    public boolean isInitialized(MsgReqGuildInviteRemove message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgReqGuildInviteRemove message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.guildid = input.readUInt32();
                    break;
                case 20:
                    message.target = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgReqGuildInviteRemove message) throws IOException
    {
        if(message.guildid != null)
            output.writeUInt32(10, message.guildid, false);

        if(message.target != null)
            output.writeUInt32(20, message.target, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
