// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgReqEquipmentDisarm implements Externalizable, Message<MsgReqEquipmentDisarm>, Schema<MsgReqEquipmentDisarm>
{

    public static Schema<MsgReqEquipmentDisarm> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgReqEquipmentDisarm getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgReqEquipmentDisarm DEFAULT_INSTANCE = new MsgReqEquipmentDisarm();

    
    private Long id;
    private Long targetHero;

    public MsgReqEquipmentDisarm()
    {
        
    }

    // getters and setters

    // id

    public boolean hasId(){
        return id != null;
    }


    public Long getId()
    {
        return id == null ? 0L : id;
    }

    public MsgReqEquipmentDisarm setId(Long id)
    {
        this.id = id;
        return this;
    }

    // targetHero

    public boolean hasTargetHero(){
        return targetHero != null;
    }


    public Long getTargetHero()
    {
        return targetHero == null ? 0L : targetHero;
    }

    public MsgReqEquipmentDisarm setTargetHero(Long targetHero)
    {
        this.targetHero = targetHero;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgReqEquipmentDisarm> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgReqEquipmentDisarm newMessage()
    {
        return new MsgReqEquipmentDisarm();
    }

    public Class<MsgReqEquipmentDisarm> typeClass()
    {
        return MsgReqEquipmentDisarm.class;
    }

    public String messageName()
    {
        return MsgReqEquipmentDisarm.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgReqEquipmentDisarm.class.getName();
    }

    public boolean isInitialized(MsgReqEquipmentDisarm message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgReqEquipmentDisarm message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.id = input.readUInt64();
                    break;
                case 30:
                    message.targetHero = input.readUInt64();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgReqEquipmentDisarm message) throws IOException
    {
        if(message.id != null)
            output.writeUInt64(10, message.id, false);

        if(message.targetHero != null)
            output.writeUInt64(30, message.targetHero, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
