// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgReqOtherBattleIdQuery implements Externalizable, Message<MsgReqOtherBattleIdQuery>, Schema<MsgReqOtherBattleIdQuery>
{

    public static Schema<MsgReqOtherBattleIdQuery> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgReqOtherBattleIdQuery getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgReqOtherBattleIdQuery DEFAULT_INSTANCE = new MsgReqOtherBattleIdQuery();

    
    private Integer userid;

    public MsgReqOtherBattleIdQuery()
    {
        
    }

    // getters and setters

    // userid

    public boolean hasUserid(){
        return userid != null;
    }


    public Integer getUserid()
    {
        return userid == null ? 0 : userid;
    }

    public MsgReqOtherBattleIdQuery setUserid(Integer userid)
    {
        this.userid = userid;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgReqOtherBattleIdQuery> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgReqOtherBattleIdQuery newMessage()
    {
        return new MsgReqOtherBattleIdQuery();
    }

    public Class<MsgReqOtherBattleIdQuery> typeClass()
    {
        return MsgReqOtherBattleIdQuery.class;
    }

    public String messageName()
    {
        return MsgReqOtherBattleIdQuery.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgReqOtherBattleIdQuery.class.getName();
    }

    public boolean isInitialized(MsgReqOtherBattleIdQuery message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgReqOtherBattleIdQuery message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.userid = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgReqOtherBattleIdQuery message) throws IOException
    {
        if(message.userid != null)
            output.writeUInt32(10, message.userid, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
