// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgRspFiefFightNpc implements Externalizable, Message<MsgRspFiefFightNpc>, Schema<MsgRspFiefFightNpc>
{

    public static Schema<MsgRspFiefFightNpc> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgRspFiefFightNpc getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgRspFiefFightNpc DEFAULT_INSTANCE = new MsgRspFiefFightNpc();

    
    private ReturnInfo ri;
    private List<HeroInfo> heroInfos;
    private LordFiefInfo lordFiefInfo;
    private FiefInfo fiefInfo;
    private Long battleid;

    public MsgRspFiefFightNpc()
    {
        
    }

    // getters and setters

    // ri

    public boolean hasRi(){
        return ri != null;
    }


    public ReturnInfo getRi()
    {
        return ri == null ? new ReturnInfo() : ri;
    }

    public MsgRspFiefFightNpc setRi(ReturnInfo ri)
    {
        this.ri = ri;
        return this;
    }

    // heroInfos

    public boolean hasHeroInfos(){
        return heroInfos != null;
    }


    public List<HeroInfo> getHeroInfosList()
    {
        return heroInfos == null?  new ArrayList<HeroInfo>():heroInfos;
    }

    public int getHeroInfosCount()
    {
        return heroInfos == null?0:heroInfos.size();
    }

    public HeroInfo getHeroInfos(int i)
    {
        return heroInfos == null?null:heroInfos.get(i);
    }


    public MsgRspFiefFightNpc setHeroInfosList(List<HeroInfo> heroInfos)
    {
        this.heroInfos = heroInfos;
        return this;    
    }

    // lordFiefInfo

    public boolean hasLordFiefInfo(){
        return lordFiefInfo != null;
    }


    public LordFiefInfo getLordFiefInfo()
    {
        return lordFiefInfo == null ? new LordFiefInfo() : lordFiefInfo;
    }

    public MsgRspFiefFightNpc setLordFiefInfo(LordFiefInfo lordFiefInfo)
    {
        this.lordFiefInfo = lordFiefInfo;
        return this;
    }

    // fiefInfo

    public boolean hasFiefInfo(){
        return fiefInfo != null;
    }


    public FiefInfo getFiefInfo()
    {
        return fiefInfo == null ? new FiefInfo() : fiefInfo;
    }

    public MsgRspFiefFightNpc setFiefInfo(FiefInfo fiefInfo)
    {
        this.fiefInfo = fiefInfo;
        return this;
    }

    // battleid

    public boolean hasBattleid(){
        return battleid != null;
    }


    public Long getBattleid()
    {
        return battleid == null ? 0L : battleid;
    }

    public MsgRspFiefFightNpc setBattleid(Long battleid)
    {
        this.battleid = battleid;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgRspFiefFightNpc> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgRspFiefFightNpc newMessage()
    {
        return new MsgRspFiefFightNpc();
    }

    public Class<MsgRspFiefFightNpc> typeClass()
    {
        return MsgRspFiefFightNpc.class;
    }

    public String messageName()
    {
        return MsgRspFiefFightNpc.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgRspFiefFightNpc.class.getName();
    }

    public boolean isInitialized(MsgRspFiefFightNpc message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgRspFiefFightNpc message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.ri = input.mergeObject(message.ri, ReturnInfo.getSchema());
                    break;

                case 20:
                    if(message.heroInfos == null)
                        message.heroInfos = new ArrayList<HeroInfo>();
                    message.heroInfos.add(input.mergeObject(null, HeroInfo.getSchema()));
                    break;

                case 30:
                    message.lordFiefInfo = input.mergeObject(message.lordFiefInfo, LordFiefInfo.getSchema());
                    break;

                case 40:
                    message.fiefInfo = input.mergeObject(message.fiefInfo, FiefInfo.getSchema());
                    break;

                case 50:
                    message.battleid = input.readUInt64();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgRspFiefFightNpc message) throws IOException
    {
        if(message.ri != null)
             output.writeObject(10, message.ri, ReturnInfo.getSchema(), false);


        if(message.heroInfos != null)
        {
            for(HeroInfo heroInfos : message.heroInfos)
            {
                if(heroInfos != null)
                    output.writeObject(20, heroInfos, HeroInfo.getSchema(), true);
            }
        }


        if(message.lordFiefInfo != null)
             output.writeObject(30, message.lordFiefInfo, LordFiefInfo.getSchema(), false);


        if(message.fiefInfo != null)
             output.writeObject(40, message.fiefInfo, FiefInfo.getSchema(), false);


        if(message.battleid != null)
            output.writeUInt64(50, message.battleid, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
