// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgReqHeroAbandon implements Externalizable, Message<MsgReqHeroAbandon>, Schema<MsgReqHeroAbandon>
{

    public static Schema<MsgReqHeroAbandon> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgReqHeroAbandon getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgReqHeroAbandon DEFAULT_INSTANCE = new MsgReqHeroAbandon();

    
    private List<Long> heros;

    public MsgReqHeroAbandon()
    {
        
    }

    // getters and setters

    // heros

    public boolean hasHeros(){
        return heros != null;
    }


    public List<Long> getHerosList()
    {
        return heros == null?  new ArrayList<Long>():heros;
    }

    public int getHerosCount()
    {
        return heros == null?0:heros.size();
    }

    public Long getHeros(int i)
    {
        return heros == null?null:heros.get(i);
    }


    public MsgReqHeroAbandon setHerosList(List<Long> heros)
    {
        this.heros = heros;
        return this;    
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgReqHeroAbandon> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgReqHeroAbandon newMessage()
    {
        return new MsgReqHeroAbandon();
    }

    public Class<MsgReqHeroAbandon> typeClass()
    {
        return MsgReqHeroAbandon.class;
    }

    public String messageName()
    {
        return MsgReqHeroAbandon.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgReqHeroAbandon.class.getName();
    }

    public boolean isInitialized(MsgReqHeroAbandon message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgReqHeroAbandon message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    if(message.heros == null)
                        message.heros = new ArrayList<Long>();
                    message.heros.add(input.readUInt64());
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgReqHeroAbandon message) throws IOException
    {
        if(message.heros != null)
        {
            for(Long heros : message.heros)
            {
                if(heros != null)
                    output.writeUInt64(10, heros, true);
            }
        }
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
