// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgReqUserRankInfo implements Externalizable, Message<MsgReqUserRankInfo>, Schema<MsgReqUserRankInfo>
{

    public static Schema<MsgReqUserRankInfo> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgReqUserRankInfo getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgReqUserRankInfo DEFAULT_INSTANCE = new MsgReqUserRankInfo();

    
    private UserRankType type;
    private Integer start;
    private Integer count;

    public MsgReqUserRankInfo()
    {
        
    }

    // getters and setters

    // type

    public boolean hasType(){
        return type != null;
    }


    public UserRankType getType()
    {
        return type == null ? UserRankType.USER_RANK_CHARGE : type;
    }

    public MsgReqUserRankInfo setType(UserRankType type)
    {
        this.type = type;
        return this;
    }

    // start

    public boolean hasStart(){
        return start != null;
    }


    public Integer getStart()
    {
        return start == null ? 0 : start;
    }

    public MsgReqUserRankInfo setStart(Integer start)
    {
        this.start = start;
        return this;
    }

    // count

    public boolean hasCount(){
        return count != null;
    }


    public Integer getCount()
    {
        return count == null ? 0 : count;
    }

    public MsgReqUserRankInfo setCount(Integer count)
    {
        this.count = count;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgReqUserRankInfo> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgReqUserRankInfo newMessage()
    {
        return new MsgReqUserRankInfo();
    }

    public Class<MsgReqUserRankInfo> typeClass()
    {
        return MsgReqUserRankInfo.class;
    }

    public String messageName()
    {
        return MsgReqUserRankInfo.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgReqUserRankInfo.class.getName();
    }

    public boolean isInitialized(MsgReqUserRankInfo message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgReqUserRankInfo message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.type = UserRankType.valueOf(input.readEnum());
                    break;
                case 20:
                    message.start = input.readUInt32();
                    break;
                case 30:
                    message.count = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgReqUserRankInfo message) throws IOException
    {
        if(message.type != null)
             output.writeEnum(10, message.type.number, false);

        if(message.start != null)
            output.writeUInt32(20, message.start, false);

        if(message.count != null)
            output.writeUInt32(30, message.count, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
