// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from client.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MsgReqRoulette implements Externalizable, Message<MsgReqRoulette>, Schema<MsgReqRoulette>
{

    public static Schema<MsgReqRoulette> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static MsgReqRoulette getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final MsgReqRoulette DEFAULT_INSTANCE = new MsgReqRoulette();

    
    private Integer type;

    public MsgReqRoulette()
    {
        
    }

    // getters and setters

    // type

    public boolean hasType(){
        return type != null;
    }


    public Integer getType()
    {
        return type == null ? 0 : type;
    }

    public MsgReqRoulette setType(Integer type)
    {
        this.type = type;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MsgReqRoulette> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MsgReqRoulette newMessage()
    {
        return new MsgReqRoulette();
    }

    public Class<MsgReqRoulette> typeClass()
    {
        return MsgReqRoulette.class;
    }

    public String messageName()
    {
        return MsgReqRoulette.class.getSimpleName();
    }

    public String messageFullName()
    {
        return MsgReqRoulette.class.getName();
    }

    public boolean isInitialized(MsgReqRoulette message)
    {
        return true;
    }

    public void mergeFrom(Input input, MsgReqRoulette message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.type = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, MsgReqRoulette message) throws IOException
    {
        if(message.type != null)
            output.writeUInt32(10, message.type, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
