// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from common.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class OtherHeroArmPropInfo implements Externalizable, Message<OtherHeroArmPropInfo>, Schema<OtherHeroArmPropInfo>
{

    public static Schema<OtherHeroArmPropInfo> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static OtherHeroArmPropInfo getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final OtherHeroArmPropInfo DEFAULT_INSTANCE = new OtherHeroArmPropInfo();

    
    private Integer type;
    private Integer value;
    private Integer maxValue;

    public OtherHeroArmPropInfo()
    {
        
    }

    // getters and setters

    // type

    public boolean hasType(){
        return type != null;
    }


    public Integer getType()
    {
        return type == null ? 0 : type;
    }

    public OtherHeroArmPropInfo setType(Integer type)
    {
        this.type = type;
        return this;
    }

    // value

    public boolean hasValue(){
        return value != null;
    }


    public Integer getValue()
    {
        return value == null ? 0 : value;
    }

    public OtherHeroArmPropInfo setValue(Integer value)
    {
        this.value = value;
        return this;
    }

    // maxValue

    public boolean hasMaxValue(){
        return maxValue != null;
    }


    public Integer getMaxValue()
    {
        return maxValue == null ? 0 : maxValue;
    }

    public OtherHeroArmPropInfo setMaxValue(Integer maxValue)
    {
        this.maxValue = maxValue;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<OtherHeroArmPropInfo> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public OtherHeroArmPropInfo newMessage()
    {
        return new OtherHeroArmPropInfo();
    }

    public Class<OtherHeroArmPropInfo> typeClass()
    {
        return OtherHeroArmPropInfo.class;
    }

    public String messageName()
    {
        return OtherHeroArmPropInfo.class.getSimpleName();
    }

    public String messageFullName()
    {
        return OtherHeroArmPropInfo.class.getName();
    }

    public boolean isInitialized(OtherHeroArmPropInfo message)
    {
        return true;
    }

    public void mergeFrom(Input input, OtherHeroArmPropInfo message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.type = input.readUInt32();
                    break;
                case 20:
                    message.value = input.readUInt32();
                    break;
                case 30:
                    message.maxValue = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, OtherHeroArmPropInfo message) throws IOException
    {
        if(message.type != null)
            output.writeUInt32(10, message.type, false);

        if(message.value != null)
            output.writeUInt32(20, message.value, false);

        if(message.maxValue != null)
            output.writeUInt32(30, message.maxValue, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
