// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from common.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class PlayerWantedInfo implements Externalizable, Message<PlayerWantedInfo>, Schema<PlayerWantedInfo>
{

    public static Schema<PlayerWantedInfo> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static PlayerWantedInfo getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final PlayerWantedInfo DEFAULT_INSTANCE = new PlayerWantedInfo();

    
    private Long id;
    private Integer country;
    private Integer userid;
    private Integer target;
    private Integer endTime;

    public PlayerWantedInfo()
    {
        
    }

    // getters and setters

    // id

    public boolean hasId(){
        return id != null;
    }


    public Long getId()
    {
        return id == null ? 0L : id;
    }

    public PlayerWantedInfo setId(Long id)
    {
        this.id = id;
        return this;
    }

    // country

    public boolean hasCountry(){
        return country != null;
    }


    public Integer getCountry()
    {
        return country == null ? 0 : country;
    }

    public PlayerWantedInfo setCountry(Integer country)
    {
        this.country = country;
        return this;
    }

    // userid

    public boolean hasUserid(){
        return userid != null;
    }


    public Integer getUserid()
    {
        return userid == null ? 0 : userid;
    }

    public PlayerWantedInfo setUserid(Integer userid)
    {
        this.userid = userid;
        return this;
    }

    // target

    public boolean hasTarget(){
        return target != null;
    }


    public Integer getTarget()
    {
        return target == null ? 0 : target;
    }

    public PlayerWantedInfo setTarget(Integer target)
    {
        this.target = target;
        return this;
    }

    // endTime

    public boolean hasEndTime(){
        return endTime != null;
    }


    public Integer getEndTime()
    {
        return endTime == null ? 0 : endTime;
    }

    public PlayerWantedInfo setEndTime(Integer endTime)
    {
        this.endTime = endTime;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<PlayerWantedInfo> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public PlayerWantedInfo newMessage()
    {
        return new PlayerWantedInfo();
    }

    public Class<PlayerWantedInfo> typeClass()
    {
        return PlayerWantedInfo.class;
    }

    public String messageName()
    {
        return PlayerWantedInfo.class.getSimpleName();
    }

    public String messageFullName()
    {
        return PlayerWantedInfo.class.getName();
    }

    public boolean isInitialized(PlayerWantedInfo message)
    {
        return true;
    }

    public void mergeFrom(Input input, PlayerWantedInfo message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.id = input.readUInt64();
                    break;
                case 20:
                    message.country = input.readUInt32();
                    break;
                case 30:
                    message.userid = input.readUInt32();
                    break;
                case 40:
                    message.target = input.readUInt32();
                    break;
                case 50:
                    message.endTime = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, PlayerWantedInfo message) throws IOException
    {
        if(message.id != null)
            output.writeUInt64(10, message.id, false);

        if(message.country != null)
            output.writeUInt32(20, message.country, false);

        if(message.userid != null)
            output.writeUInt32(30, message.userid, false);

        if(message.target != null)
            output.writeUInt32(40, message.target, false);

        if(message.endTime != null)
            output.writeUInt32(50, message.endTime, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
