// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from common.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class PokerInfo implements Externalizable, Message<PokerInfo>, Schema<PokerInfo>
{

    public static Schema<PokerInfo> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static PokerInfo getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final PokerInfo DEFAULT_INSTANCE = new PokerInfo();

    
    private Integer index;
    private Integer result;
    private Integer count;

    public PokerInfo()
    {
        
    }

    // getters and setters

    // index

    public boolean hasIndex(){
        return index != null;
    }


    public Integer getIndex()
    {
        return index == null ? 0 : index;
    }

    public PokerInfo setIndex(Integer index)
    {
        this.index = index;
        return this;
    }

    // result

    public boolean hasResult(){
        return result != null;
    }


    public Integer getResult()
    {
        return result == null ? 0 : result;
    }

    public PokerInfo setResult(Integer result)
    {
        this.result = result;
        return this;
    }

    // count

    public boolean hasCount(){
        return count != null;
    }


    public Integer getCount()
    {
        return count == null ? 0 : count;
    }

    public PokerInfo setCount(Integer count)
    {
        this.count = count;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<PokerInfo> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public PokerInfo newMessage()
    {
        return new PokerInfo();
    }

    public Class<PokerInfo> typeClass()
    {
        return PokerInfo.class;
    }

    public String messageName()
    {
        return PokerInfo.class.getSimpleName();
    }

    public String messageFullName()
    {
        return PokerInfo.class.getName();
    }

    public boolean isInitialized(PokerInfo message)
    {
        return true;
    }

    public void mergeFrom(Input input, PokerInfo message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.index = input.readUInt32();
                    break;
                case 20:
                    message.result = input.readUInt32();
                    break;
                case 30:
                    message.count = input.readUInt32();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, PokerInfo message) throws IOException
    {
        if(message.index != null)
            output.writeUInt32(10, message.index, false);

        if(message.result != null)
            output.writeUInt32(20, message.result, false);

        if(message.count != null)
            output.writeUInt32(30, message.count, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
