// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from common.proto

package com.vikings.sanguo.protos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class UserTroopInfos implements Externalizable, Message<UserTroopInfos>, Schema<UserTroopInfos>
{

    public static Schema<UserTroopInfos> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static UserTroopInfos getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final UserTroopInfos DEFAULT_INSTANCE = new UserTroopInfos();

    
    private DataCtrl ctrl;
    private List<ExUserTroopInfo> infos;

    public UserTroopInfos()
    {
        
    }

    // getters and setters

    // ctrl

    public boolean hasCtrl(){
        return ctrl != null;
    }


    public DataCtrl getCtrl()
    {
        return ctrl == null ? new DataCtrl() : ctrl;
    }

    public UserTroopInfos setCtrl(DataCtrl ctrl)
    {
        this.ctrl = ctrl;
        return this;
    }

    // infos

    public boolean hasInfos(){
        return infos != null;
    }


    public List<ExUserTroopInfo> getInfosList()
    {
        return infos == null?  new ArrayList<ExUserTroopInfo>():infos;
    }

    public int getInfosCount()
    {
        return infos == null?0:infos.size();
    }

    public ExUserTroopInfo getInfos(int i)
    {
        return infos == null?null:infos.get(i);
    }


    public UserTroopInfos setInfosList(List<ExUserTroopInfo> infos)
    {
        this.infos = infos;
        return this;    
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<UserTroopInfos> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public UserTroopInfos newMessage()
    {
        return new UserTroopInfos();
    }

    public Class<UserTroopInfos> typeClass()
    {
        return UserTroopInfos.class;
    }

    public String messageName()
    {
        return UserTroopInfos.class.getSimpleName();
    }

    public String messageFullName()
    {
        return UserTroopInfos.class.getName();
    }

    public boolean isInitialized(UserTroopInfos message)
    {
        return true;
    }

    public void mergeFrom(Input input, UserTroopInfos message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 10:
                    message.ctrl = input.mergeObject(message.ctrl, DataCtrl.getSchema());
                    break;

                case 20:
                    if(message.infos == null)
                        message.infos = new ArrayList<ExUserTroopInfo>();
                    message.infos.add(input.mergeObject(null, ExUserTroopInfo.getSchema()));
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, UserTroopInfos message) throws IOException
    {
        if(message.ctrl != null)
             output.writeObject(10, message.ctrl, DataCtrl.getSchema(), false);


        if(message.infos != null)
        {
            for(ExUserTroopInfo infos : message.infos)
            {
                if(infos != null)
                    output.writeObject(20, infos, ExUserTroopInfo.getSchema(), true);
            }
        }

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
